// Generated by tools/export_journey_layout.py: metric projection + reviewed paint calibration.
using System.Numerics;
namespace Atland;
public static class JourneyLayout
{
    public static readonly Vector2[] Ground={new(184.16f,619.87f),new(768.0f,956.94f),new(1351.84f,619.87f),new(768.0f,282.79f)};
    public static readonly Vector2[] WarehouseObstacle={new(679.0f,566.0f),new(790.0f,621.0f),new(883.0f,573.0f),new(766.0f,523.0f)};
    public static readonly Vector2 WarehouseEntry=new(975.0f,435.0f);
    public static readonly Vector2 WarehouseExit=new(768.0f,872.67f);
    public static readonly Vector2 Whetstone=new(542.0f,650.0f);
    public static readonly Vector2 Manifest=new(359.31f,619.87f);
    public static readonly Vector2 Winch=new(1074.51f,678.85f);
    public static readonly Vector2 ShoreEntry=new(768.0f,367.06f);
    public static readonly Vector2[] Survey={new(568.0f,537.0f),new(849.0f,778.0f),new(1054.0f,586.0f)};
    public static readonly Vector2 Reveal=new(768.0f,619.87f);
    public static readonly Vector2 ShoreExit=new(768.0f,872.67f);
    public static readonly Vector2[] WarehouseSpawns={new(549.06f,577.73f),new(768.0f,788.4f),new(1016.13f,645.15f)};
    public static readonly Vector2[] ShoreSpawns={new(476.08f,619.87f),new(768.0f,788.4f),new(1059.92f,619.87f)};
    public static readonly Vector2[] WarehouseGround={new(225.0f,600.0f),new(777.0f,910.0f),new(1280.0f,605.0f),new(790.0f,324.0f)};
}
