#!/usr/bin/env python3
"""Combine metric blockout projections with reviewed painted prop coordinates."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1];src=root/'assets/source/journey'
layout=json.loads((src/'layout.json').read_text());layout.update(json.loads((src/'paint-calibration.json').read_text()))
lines=['// Generated by tools/export_journey_layout.py: metric projection + reviewed paint calibration.','using System.Numerics;','namespace Atland;','public static class JourneyLayout','{']
def vec(p):return f'new({p[0]}f,{p[1]}f)'
for key,value in layout.items():
 if key in ['metres_per_standing_adult','standing_pixels','image_size']:continue
 array=isinstance(value[0],list);name=key[0].upper()+key[1:]
 lines.append('    public static readonly Vector2'+('[]' if array else '')+' '+name+'='+('{'+','.join(map(vec,value))+'}' if array else vec(value))+';')
(root/'scripts/JourneyLayout.cs').write_text('\n'.join(lines+['}'])+'\n')
